config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    resources :posts
    resources :projects
    resources :contacts, only: [:new, :create]
    get 'welcome/index'
    root 'welcome#index'

    get '*path' => redirect('/')
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :nazwa, :validate => true
  attribute :email, :validate => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  attribute :message, :validate => true
  attribute :nickname, :captcha => true

def headers
        {

          :subject => "Contact Form",
           :to => "maricha177@gmail.com",
           :from => %("#{nazwa}" <#{email}>)
        }
      end
end

app/models/post.rb
class Post < ActiveRecord::Base

extend FriendlyId
friendly_id :title, use: :slugged


end

app/models/project.rb
class Project < ActiveRecord::Base
extend FriendlyId
friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Connot send message.'
      render :new
    end
  end


def contact
    params.require(:contact).permit(:nazwa, :email, :message, :nickname)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :find_post, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!, except: [:index, :show]
  def index

    @posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 1)

  end

  def new
      @post = Post.new
  end

  def create
      @post = Post.new post_params

      if @post.save
        redirect_to @post, notice: "Hellz yeah, Your article success saved"
      else
        render 'new', notice: "Oh no, nie da sie zapisac bo nie!"
      end
  end

  def show

  end

  def edit
  end

  def update

      if @post.update post_params
        redirect_to @post, notoice: "pozytywanie update"
      else
       render 'edit'
     end
  end


  def destroy
    @post.destroy
    redirect_to posts_path
  end





  private

  def post_params

      params.require(:post).permit(:title, :content, :slug)

  end

  def find_post
      @post = Post.friendly.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
    def index
          @projects = Project.all.order("created_at desc")
    end

    def show

    end

    def new
      @project = Project.new
    end


    def edit
    end

    def update
        if @project.update project_params
          redirect_to @project, notice: "dobre"
        else
          render 'edit'
        end
    end

    def destroy
      @project.destroy
      redirect_to projects_path
    end

    def create
      @project = Project.new project_params

      if @project.save
        redirect_to @project, notice: "Udalo sie"
      else
        render 'new'
      end
    end

    private

    def find_project
      @project =Project.friendly.find(params[:id])
    end

    def project_params
        params.require(:project).permit(:title, :description, :link, :slug)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @posts = Post.all.limit(3).order("created_at desc")
    @projects = Project.all.limit(3).order("created_at desc")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end
  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {

        autolink: true,
        no_intra_emphasis: true,
        disable_indented_code_blocks: true,
        fenced_code_blocks: true,
        lax_html_blocks: true,
        strikethrough: true,
        superscript: true

    }

    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h1 id="page_title">Cześć!</h1>
<div class="wrapper_padding skinny_wrapper">

  <h1>Dziękuje za wiadomość!</h1>
  <p>Odpiszę jak najszybciej się da.</p>


</div>

app/views/contacts/new.html.erb
<h1 id="page_title">Cześć!</h1>

<div class="wrapper_padding skinny_wrapper">
<%= form_for @contact do |f| %>
    <%= f.label :nazwa %> <br />
    <%= f.text_field :nazwa, required: true %>

    <br/>

    <%= f.label :email %> <br />
    <%= f.text_field :email, required: true %>

    <br/>

     <%= f.label :treść %> <br />
     <%= f.text_field :message, as: :text %>

     <div class="hidden">
       <%= f.label :nickname %> <br />
      <%= f.text_field :nickname, hint: 'pozostaw to puste' %>

      </div>

      <%= f.submit 'Wyśli wiadomość', class: "button" %>

      <br/ >


    <% end %>

<br/ >
<br/ >

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <meta charset="UTF-8">
  <title>Porfolio</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

  <link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <header id ="main_navigation" class="clearfix">
        <%= link_to "Red Star Company", root_path, class: "name" %>

              <nav>
                    <%= link_to "Artykuły", posts_path %>

                    <%= link_to "Projekty", projects_path %>
                    <%= link_to "Kontakt", new_contact_path %>
                    <% if user_signed_in? %>
                    <%= link_to "Wyloguj", destroy_user_session_path, method: :delete %>
                    <% end %>
              </nav>



    </header>

  <% if notice %>
    <p class="notice"><%= notice %> </p>
    <% elsif alert %>
    <p class="alert"><%= alert %></p>
    <% end %>

<%= yield %>


<footer id="main_footer">

<p class="copyright">&copy;  2015 Marcin Starmach</p>
<nav>

    <a href="http://twitter.com/God" target="_blank"><i class="fa fa-twitter"></i></a>
    <a href="http://facebook.com/marcin.starmach" target="_blank"><i class="fa fa-facebook"></i></a>
    <a href="http://github.com/Maricha" target="_blank"><i class="fa fa-github"></i></a>
</nav>


</footer>
</body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>


   var disqus_config = function () {
       this.page.shorname = 'redstarcomapny';
       this.page.url = '<%= url_for([@post, {only_path: false}]) %>';
        this.page.identifier = '<%= @post.id %>';
       this.page.title =  '<%= @post.title %>';
    };
    /**
     *

     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
     */
    /*
    var disqus_config = function () {
        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() {  // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');

        s.src = '//redstarcompany.disqus.com/embed.js';

        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

<% if @post.errors.any? %>
  <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>

   <% end %>

   <%= f.label :title %> <br/>
   <%= f.text_field :title %> <br/>

    <br/>
    </br/>

    <%= f.label :content, "Napisz tutaj swój artykół" %> <br/>
    <%= f.text_area :content %> <br/>

    <br/>
    <br/>

    <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1  id="page_title">Edytuj post</h1>

<div class="skinny_wrapper wrapper_padding">


<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<h1 id="page_title">Artykuły</h1>

<div id="posts_wrapper" class="skinny_wrapper">

<%@posts.each do |post| %>

        <div class="post">

            <p class="date"><%= post.created_at.strftime('%A, %B %d')  %></p>

              <h2><%= link_to post.title, post %></h2>
              <hr>
        </div>
<% end %>

</div>




<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1 id="page_title">Nowy artykuł</h1>


<div class="skinny_wrapper wrapper_padding">

<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">

        <header>


          <p class="date"><%= @post.created_at.strftime('%A, %B %d') %></p>
          <h1><%= @post.title %></h1>
          <hr>
        </header>



  <div id="content">

        <%= markdown @post.content %>
  </div>

  <% if user_signed_in? %>
         <div id="admin_links">

            <%= link_to "Edytuj Artykuł", edit_post_path(@post) %>
            <%= link_to "Usuń", post_path(@post), method: :delete, data: {cofirm: "Jesteś pewien?"} %>


         </div>
        <% end %>

  <hr>

  <div id="share_box">

    <p>Sheruj :)</p>

    <a onclick="javascript:window.open('http://twitter.com/share?text=<%= @post.title %> by @rsc - &amp;url=<%= url_for([@post, {only_path: false}]) %>',  '_blank', 'width=800,  height=500, top=200, left=300');void(0);"><i class="fa fa-twitter"></i></a>

    <a onclick="javascript:window.open('http://facebook.com/sharer.php?u=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-facebook"></i></a>

    <a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@post, {only_path: false}]) %>',  '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-google-plus"></i></a>

  </div>
<hr>

  <%= render 'disqus' %>
</div>

<script id="dsq-count-scr" src="//redstarcompany.disqus.com/count.js" async></script>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>

<% if @project.errors.any? %>
  <h2><%= pluralize(@post.errors.count, "error") %> prevented this project from saving:</h2>
    <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>

   <% end %>

   <%= f.label :title %> <br/>
   <%= f.text_field :title %> <br/>

    <br/>
    </br/>

    <%= f.label :description %> <br/>
    <%= f.text_area :description %> <br/>

    <br/>
    <br/>

    <%= f.label :link %> <br/>
    <%= f.text_field :link %> <br/>

    <br/>
    <br/>

    <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h1 id="page_title">Edytuj projekt</h1>

<div class="skinny_wrapper wrapper_padding">


<%= render 'form' %>
</div>

app/views/projects/index.html.erb
<h1 id="page_title">Projekty</h1>

<div id="posts_wrapper" class="skinny_wrapper">

<%@projects.each do |project| %>

        <div class="post">

            <p class="date"><%= project.created_at.strftime('%A, %B %d')  %></p>

              <h2><%= link_to project.title, project %></h2>
              <hr>
        </div>
<% end %>

</div>

app/views/projects/new.html.erb
 <h1 id = "page_title">Nowy project</h1>

<div class="skinny_wrapper wrapper_padding">



  <%= render  'form' %>
</div>

app/views/projects/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">

        <header>


          <p class="date"><%= @project.created_at.strftime('%A, %B %d') %></p>
          <h1><%= @project.title %></h1>
          <hr>
        </header>



  <div id="content">

        <%= markdown @project.description %>
    <div class="button_wrapper">
        <a href="<%= @project.link %>" class="project_button"  target ="_blank"> Odwiedź <%=@project.title %>
        </a>
        </div>




  </div>

  <% if user_signed_in? %>
         <div id="admin_links">

            <%= link_to "Edit Article", edit_project_path(@project) %>
            <%= link_to "Delete Article", project_path(@project), method: :delete, data: {cofirm: "Are you suer?"} %>


         </div>
        <% end %>


  <hr>

app/views/welcome/index.html.erb
<div class="wrapper wrapper_padding clearfix">

        <div class="col-1 homepage_content about">

                <h2>O co chodzi?</h2>
                <hr>
                <p>
                  Cześć! Nazywam się Marcin Starmach i jestem uczniem.. tak to dobre stwierdzenie :)</p>
                  <p>Może kiedyś będą miał zaszczyt powiedzieć o sobie, że jestem Web Developer'em</p>
                  <p>Staram się ogarnąc Ruby on Rails oraz JavaScript. Z racji nauki w szkole, coś tam piszę w PHP.</p>
                  <p>ZSP5 w Jaworznie, więcej tutaj <a href="http://www.zsp5.jaworzno.pl/">Darwin</a>.

                    </p>

        </div>
        <div class="col-2 homepage_content">
                  <h2>Napisane akrtykuły</h2>
                  <hr>

                  <% @posts.each do |post| %>
                      <h3><a href="#"><%=link_to post.title, post %></a></h3>
                      <p class="date"><%= post.created_at.strftime("%A, %b %d") %></p>
                  <% end %>


        </div>

        <div class="col-3 homepage_content">
                  <h2>Stworzone projekty</h2>
                  <hr>
                  <% @projects.each do |project| %>
                      <h3><a href="#"><%=link_to project.title, project %></a></h3>
                      <p class="date"><%= project.created_at.strftime("%A, %b %d") %></p>
                  <% end %>

        </div>

    </div>